import * as mongoose from 'mongoose';

export const UserSchema = new mongoose.Schema({
    userName: {type: String},
    userPhone: {type: String},
    userEmail: {type: String, unique: true},
    userRole: {type: String},
    userIsBlock: {type: Boolean},
    userPassword: {type: String},
    userType: {type: String},
    userAvatar: {type: String},
    refreshToken: {type: String},
    userSecret: {type: String},
    userGender: {type: String},
	userEthnicity: {type: String},
	userNationality: {type: String},
	userBirthday: {type: Date},
	userBirthplace: {type: String},
	userContactAddress: {type: String},
	userProvinceResidence: {type: String},
	userDistrictResidence: {type: String},
	userAddress12: {type: String},
	userSchool12: {type: String},
	userAddress11: {type: String},
	userSchool11: {type: String},
	userAddress10: {type: String},
	userSchool10: {type: String},
    userIdentityNumber: {type: String},
	userWardResidence: {type: String},
	userStreetResidence: {type: String},
    currentTokenDevice: {type: String},
    oldTokenDevice: {type: String}
})

export interface User {
    userId: string,
    userRefreshToken: string,
    userName: string,
    userPhone: string,
    userEmail: string,
    userRole: string,
    userIsBlock: boolean,
    userPassword: string,
    userType: string,
    userAvatar: string,
    userSecret: string,
    userGender: string,
	userEthnicity: string,
	userNationality: string,
	userBirthday: Date,
	userBirthplace: string,
	userContactAddress: string,
	userProvinceResidence: string,
	userDistrictResidence: string,
	userAddress12: string,
	userSchool12: string,
	userAddress11: string,
	userSchool11: string,
	userAddress10: string,
	userSchool10: string,
    userIdentityNumber: string,
	userWardResidence: string,
	userStreetResidence: string,
    currentTokenDevice: string,
    oldTokenDevice: string
}
